// <auto-generated />
namespace DATNwebtintuc.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addcommentlan2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcommentlan2));
        
        string IMigrationMetadata.Id
        {
            get { return "202208031514336_addcommentlan2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
