// <auto-generated />
namespace DATNwebtintuc.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ad));
        
        string IMigrationMetadata.Id
        {
            get { return "202206130720465_ad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
